spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/guide?zeroDateTimeBehavior=convertToNull&characterEncoding=UTF-8&&serverTimezone=Asia/Seoul
    username: ramos
    password: test123
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 20
  jpa:
    open-in-view: false
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQLDialect
springdoc:
  swagger-ui:
    path: /api-docs
  api-docs:
    groups:
      enabled: true
  cache:
    disabled: true